"""
FastAPI Dependencies for dependency injection.
"""
from fastapi import Request
from core.providers.factory import ProviderFactory
from core.intelligence.engine import ConversationEngine
from config import settings

def get_provider_factory():
    """Returns the ProviderFactory class/singleton."""
    return ProviderFactory

def get_conversation_engine():
    """Returns the ConversationEngine class."""
    return ConversationEngine

def get_settings():
    """Returns the application configuration settings."""
    return settings

def get_request_id(request: Request) -> str:
    """Extracts the request ID generated by the middleware."""
    return getattr(request.state, "request_id", "unknown")
